version: '2'
services:
  todo:
    container_name: todo
    build:
      context: .
      args:
        - MODE=${MODE}
        - APP_NAME=todo
    ports:
      - "${PORT1}:${VPORT1}"
      - "${PORT2}:${VPORT2}"
    volumes:
      - "${APP_PATH}:/var/www/html/todo"
    env_file:
      - .env
