default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: database
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  username: todo_development
  database: todo_development

test:
  <<: *default
  username: todo_test
  database: todo_test

production:
  <<: *default
  database: todo
  username: todo
  password: <%= ENV['TODO_DATABASE_PASSWORD'] %>
