default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: database
  username: root
  password:

development:
  <<: *default
  database: todo_development

test:
  <<: *default
  host: <%= ENV['TODO_TEST_DATABASE_HOST'] || 'database' %>
  database: todo_test

production:
  <<: *default
  database: todo
  username: todo
  password: <%= ENV['TODO_DATABASE_PASSWORD'] %>
